name: ShellScript

on: push

jobs:
    shellscript:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses:  actions/checkout@v7.0.1

        - name: list repo files
          run:  ls -ltra

        - name: executing shell script
          run:  ./ascii-script.sh
            